version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.20.0-browsers
    branches:
      only:
        - trunk
        - /^nshttpd.*/
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run: make dockerhub
