version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.18.10     
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
      - run: 
          command: |
            export PATH=$PATH:$GOPATH/bin
            export SHORTSHA=${CIRCLE_SHA1:0:8}
            
            make utils
      - run:
          command: |
            export PATH=$PATH:$GOPATH/bin
            export SHORTSHA=${CIRCLE_SHA1:0:8}
            make deploy
      - run:
          command: |
            export PATH=$PATH:$GOPATH/bin
            export SHORTSHA=${CIRCLE_SHA1:0:8}
            make dockerhub