version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.17-buster-node-browsers-legacy
    branches:
      only:
        - trunk
        - /^nshttpd.*/
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run: make dockerhub
