version: 2.1
jobs:
  build:
    environment:
      SHORTSHA: $(git rev-parse --short HEAD)
    docker:
      - image: cimg/go:1.18.10     
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
      - run: env PATH=$PATH:$GOPATH/bin make utils
      - run: env PATH=$PATH:$GOPATH/bin make deploy
      - run: env PATH=$PATH:$GOPATH/bin make dockerhub