version: 2.1
jobs:
  build:
    environment:
      SHORTSHA: $(git rev-parse --short HEAD)
    docker:
      - image: cimg/go:1.18.10     
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
      - run: 
          environment: 
            PATH: "$PATH:$GOPATH/bin"
            SHORTSHA: "${CIRCLE_SHA1:0:8}" 
          command: |
            make utils
      - run:
          environment: 
            PATH: "$PATH:$GOPATH/bin"
            SHORTSHA: "${CIRCLE_SHA1:0:8}"  
          command: |
            make deploy
      - run:
          environment: 
            PATH: "$PATH:$GOPATH/bin"
            SHORTSHA: "${CIRCLE_SHA1:0:8}"  
          command: |
            make dockerhub