version: 2
jobs:
  build:
    environment:
      SHORT_GIT_HASH: $(echo $CIRCLE_SHA1 | cut -c -7)
    docker:
      - image: cimg/go:1.18.10
    branches:
      only:
        - trunk
        - /^nshttpd.*/
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run: env PATH=$PATH:$GOPATH/bin make dockerhub
